fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
    yumrepo_core:
      repo: git://github.com/puppetlabs/puppetlabs-yumrepo_core
      puppet_version: ">= 6.0.0"
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
    remote_file:
      repo: git://github.com/lwf/puppet-remote_file.git
    dsc:
      repo: git://github.com/puppetlabs/puppetlabs-dsc.git
    acl:
      repo: git://github.com/puppetlabs/puppetlabs-acl.git
    powershell:
      repo: git://github.com/puppetlabs/puppetlabs-powershell.git
    sensu:
      repo: git://github.com/sensu/sensu-puppet.git
    # Needed by sensu module
    datacat:
      repo: git://github.com/richardc/puppet-datacat.git
  symlinks:
    sensuclassic: "#{source_dir}"
